#!/bin/bash
#SBATCH --job-name=WGS_meTAline
#SBATCH --workdir=.
#SBATCH --output=./smk-%j.out
#SBATCH --error=./smk-%j.err
#SBATCH --time=02:00:00
#SBATCH --ntasks=2
#SBATCH --cpus-per-task=48
#SBATCH --mail-type=end
#SBATCH --mail-user=diego.fuentes@bsc.es
#SBATCH --qos=debug
#SBATCH --constraint=highmem
module load ANACONDA/5.0.1
####################################

/apps/GREASY/2.2/INTEL/IMPI/bin/greasy  joblist.txt
