#!/bin/bash

#SBATCH --job-name=metaline_samples
#SBATCH --qos=gp_bscls
#SBATCH --account=bsc40
#SBATCH --output=/gpfs/projects/bsc40/current/okhannous/MeTAline_paper/BMC_version/raw_data/OUT/err_out/jobnm_%j.out # Output file, where
#SBATCH --error=/gpfs/projects/bsc40/current/okhannous/MeTAline_paper/BMC_version/raw_data/OUT/err_out/jobnm_%j.err # File where the error is written

#SBATCH --array=1-2 # The number of jobs in the array
#SBATCH --ntasks=2 # The number of parallel tasks
#SBATCH --tasks-per-node=2
#SBATCH --cpus-per-task=24 # Number of CPUs per run task
#SBATCH --constraint=highmem
#SBATCH --time=24:00:00

module load greasy
# Print the task id
$(sed -n "${SLURM_ARRAY_TASK_ID}p" /gpfs/projects/bsc40/current/okhannous/MeTAline_paper/BMC_version/raw_data/OUT/list_greasy.txt)
