#!/bin/bash

#SBATCH --job-name=metaline_singularity_test # Job’s name (to trace in)
#SBATCH --output=/data/projects/my_project/current/metaline_testing/metaline-test-output/err_out/jobnm_%j.out # Output file, where
#SBATCH --error=/data/projects/my_project/current/metaline_testing/metaline-test-output/err_out/jobnm_%j.err # File where the error is written

#SBATCH --ntasks=1 # The number of parallel tasks
#SBATCH --cpus-per-task=24 # Number of CPUs per run task
#SBATCH --tasks-per-node=1 # The number of allocated task/node

#SBATCH --qos=your_quality_of_service # The queue for the job
#SBATCH --account=my_account
#SBATCH --time=24:00:00 # The time you request for the job
#SBATCH --constraint=highmem # To run in highmem nodes

module load singularity

singularity run --cleanenv metaline.sif metaline-generate-config \
    --config-file test_kraken2_standard.json \
    --extension fq.gz \
    --basedir /data/projects/my_project/metaline_testing/metaline-test-output \
    --reads-directory /data/projects/my_project/metaline_testing/raw_reads_data \
    --reference-genome /data/projects/my_project/metaline_testing/reference_genome \
    --krakendb /data/projects/my_project/metaline_testing/WGS/KRAKEN2_DB/microbiome_db \
    --sample-barcode metaline_test_barcode \
    --fastq-prefix PONSJIG_165.E5-NEB-UDI \
    --metaphlan-db /data/projects/my_project/metaline_testing/Metaphlan4/db \
    --metaphlan-index mpa_testing_index \
    --n-db /data/projects/my_project/metaline_testing/WGS/humann_db \
    --protein-db /data/projects/my_project/metaline_testing/WGS/uniref

singularity run --cleanenv metaline.sif \
    metaline \
    -r all \
    -j 16 \
    --configfile test_kraken2_standard.json
