name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image for the test
      run: IMAGE_TAG="meTAline:$(date +'%Y-%m-%d')" && docker build . --file Dockerfile --tag $IMAGE_TAG  
    - name: Verify the Docker image
      run: docker images $IMAGE_TAG
